In [20]:
import torch

x = torch.arange(4).reshape(1, 4)
print(x)
print(x.max(1))
x.max(1).indices.view(1, 1)

tensor([[0, 1, 2, 3]])
torch.return_types.max(
values=tensor([3]),
indices=tensor([3]))


tensor([[3]])

In [28]:
x = torch.arange(5, dtype=torch.float)
print(x)
means = x.unfold(0, 3, 1).mean(1)
print(means)

tensor([0., 1., 2., 3., 4.])
tensor([1., 2., 3.])


In [30]:
non_final_mask = torch.tensor(tuple(map(lambda s: s is not None,
                                        [0, 0, 0, None, 0, None])), dtype=torch.bool)
print(non_final_mask)

tensor([ True,  True,  True, False,  True, False])


In [32]:
# non_final_next_states = torch.cat([s for s in [0, 0, 0, None, 0, None] if s is not None])
# print(non_final_next_states)
[s for s in [0, 0, 0, None, 0, None] if s is not None]


[0, 0, 0, 0]